### ISSUE TITLE
你的迁移文件有一个sql错误

### ISSUE THREAD

**Issue by hhniao** [rubinliudongpo/airad#1]
2018/04/13 11:51:00 INFO     ▶ 0009 |> 2018/04/13 11:50:58.565 [E] execute error                                                                                                                                                                                               : Error 1064: You have an error in your SQL syntax; check the manual that corres                                                                                                                                                                                               ponds to your MariaDB server version for the right syntax to use near 'ADD so2 v                                                                                                                                                                                               archar(10)' at line 1

错误位置: 
20171109_164549_airad.go 23行, 末尾 缺少一个逗号.

`// Run the migrations
func (m *AirAd_20171109_164549) Up() {
	m.SQL("ALTER TABLE air_ad ADD createdAt int, ADD nh3 varchar(10), " +
		"ADD co varchar(10), ADD pm25 varchar(10), ADD pm10 varchar(10), ADD o3 varchar(10)" +
			"ADD so2 varchar(10)")

}`

`// Run the migrations
func (m *AirAd_20171109_164549) Up() {
	m.SQL("ALTER TABLE air_ad ADD createdAt int, ADD nh3 varchar(10), " +
		"ADD co varchar(10), ADD pm25 varchar(10), ADD pm10 varchar(10), ADD o3 varchar(10)," +
			"ADD so2 varchar(10)")

}`

**Comment by hhniao** [comment]
还有你的依赖描述缺少 https://github.com/lib/pq

**Comment by rubinliudongpo** [comment]
其实Beego不需要数据迁移，自动检测更model更新，在线热编译，请试下

**Comment by rubinliudongpo** [comment]
其实Beego不需要数据迁移，自动检测model更新，在线热编译，请试下

**Comment by hhniao** [comment]
其实我不懂. 才学了没几天. 你的代码死活跑不起来.现在研究那个pp apiadmin去了. 好像也是你的.

**Comment by rubinliudongpo** [comment]
代码已经更新，删除了migration相关的文件，请重新拉取测试。

**Comment by rubinliudongpo** [comment]
目前主要支持MySQL，暂时不考虑PostgresSQL

**Comment by rubinliudongpo** [comment]
fixed
