### ISSUE TITLE
register db problem

### ISSUE THREAD

**Issue by zychappy** [rubinliudongpo/airad#2]
[ORM]2018/11/23 16:21:16 register db Ping `default`, Error 1044: Access denied for user 'gouser'@'%' to database 'airad'
must have one register DataBase alias named `default`

**Comment by rubinliudongpo** [comment]
I will take a look at it this weekend.

**Comment by rubinliudongpo** [comment]
Can you login MySql by 
```java
mysql -ugouser -pYOUR_GOUSER_PASSWORD  -h 127.0.0.1
```
if not ,please authorize airad access to gouser by 
```java
mysql -uroot -pYOURROOTPASSWORD  -h 127.0.0.1 -e "grant all privileges on airad.* to gouser@'%' identified by 'your_gouser_password';"
```

**Comment by zychappy** [comment]
privileges problem,it works,THX
