### ISSUE TITLE
import 依赖的问题

### ISSUE THREAD

**Issue by yiliang114** [rubinliudongpo/airad#3]
首先说一下我是个新手，我遇到的问题是，这里很多 import 依赖的方式都是 
```
import (
	_ "github.com/rubinliudongpo/airad/routers"
	"github.com/rubinliudongpo/airad/utils"

	"github.com/astaxie/beego"
	"github.com/rubinliudongpo/airad/controllers"
)
```
类似于这样的。。

为啥不是
```
import (
	_ "airad/routers"
	"airad/utils"

	"github.com/astaxie/beego"
	"airad/controllers"
)
```
这样的绝对路径的方式来 import , 因为貌似看的几个 beego 项目里都是绝对路径的形式，而且貌似 idea 里面使用 `github.com/xxx/yyy` 这样的路径，会默认打开 `GOPATH` 里面的（airad项目下的）文件

**Comment by mlkr** [comment]
https://segmentfault.com/q/1010000010846304

**Comment by rubinliudongpo** [comment]
Pls follow steps in http://sourabhbajaj.com/mac-setup/Go/README.html
